### ISSUE TITLE
Unstable Flowblade and Unloadable Project

### ISSUE THREAD

**Issue by Pyork** [jliljebl/flowblade-forum#10]
Dear Janne, dear team,

first of all I am just thankful for this brilliant product you delivered in your freetime, anyhow, thank you!

I started a quite huge project of 90 minutes 4k video with Flowblade enthusiastically and feel lost now. I can't load the recent project file anymore and Flowblade was often crashing before, I had the impression because of high performance needs.

Could you please support me by any chance? I would love to donate or to contribute in documentation work for your support. Please come back on me, my deadline is pressing, the 21th of July.

This system environment is given:
- Fresh Ubuntu 9.4 installation on a board with i5-2500 processor, 16 GB RAM and SSDs only. 
- I installed Flowblade by the Ubuntu software repository in version 2.0-1
- Nothing else specifically has been manually installed next to that.
- I verified the dependencies for gir1.2 and Python, it's fine. 

Most of all, I need the recent [linked project file](https://www.dropbox.com/sh/pthcqsb4gs6o27w/AADPGIfxvjxHTVNEHb5RKY4ta?dl=0) rescued. A one day older project file is in that folder too. This one I still can load.

Thank you so much!
Kind regards
Pyork

**Comment by Pyork** [comment]
I may better complete my issue with the following details.

My system stated by Flowblade in the shell:

FLOWBLADE MOVIE EDITOR 2.0
--------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 6.12.0
numpy version: 1.16.2
Application version: 2.0.0
OS: Ubuntu 19.04
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 8.3.0]
GTK+ version: 3.24.8
User dir: /home/pyork/.flowblade/
Locale: de_DE
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: premiere.xml
Loading shortcuts: Premiere-ish/ US keyboard
Gtk version is 3.24.8, Flowblade theme is available.
Screen size: 3600 x 1080
Small height: False
Small width: False
Detecting environment...

Loading the projects I get stated that:

Loading Project, SAVEFILE_VERSION: 5
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/app.py", line 322, in <lambda>
    window_resize_id = gui.editor_window.window.connect("size-allocate", lambda w, e:updater.window_resized())
  File "/usr/share/flowblade/Flowblade/updater.py", line 127, in window_resized
    current_sequence().resize_tracks_to_fit(gui.tline_canvas.widget.get_allocation())
  File "/usr/share/flowblade/Flowblade/editorstate.py", line 152, in current_sequence
    return project.c_seq
AttributeError: Project instance has no attribute 'c_seq'
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4abdece9c0] st: 0 edit list: 1 Missing key frame while searching for timestamp: 3600
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4abdece9c0] st: 0 edit list 1 Cannot find an index entry before timestamp: 3600.
...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4ab602e180] st: 0 edit list 1 Cannot find an index entry before timestamp: 3600.
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 91, in <module>
    app.main(modules_path)
  File "/usr/share/flowblade/Flowblade/app.py", line 376, in main
    [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4ab60206c0] st: 0 edit list: 1 Missing key frame while searching for timestamp: 3600
...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4aa8d76b00] st: 0 edit list 1 Cannot find an index entry before timestamp: 3600.
Gtk.main()
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1630, in main
    return _Gtk_main(*args, **kwargs)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4aa8d42f00] st: 0 edit list: 1 Missing key frame while searching for timestamp: 3600
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4aa8d42f00] st: 0 edit list 1 Cannot find an index entry before timestamp: 3600.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4aa8aab240] st: 0 edit list: 1 Missing key frame while searching for timestamp: 3600
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4aa8aab240] st: 0 edit list 1 Cannot find an index entry before timestamp: 3600.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4aa8d3d940] st: 0 edit list: 1 Missing key frame while searching for timestamp: 3600
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4aa8d3d940] st: 0 edit list 1 Cannot find an index entry before timestamp: 3600.
  File "/usr/lib/python2.7/dist-packages/gi/_ossighelper.py", line 251, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4aa8a4bc40] st: 0 edit list: 1 Missing key frame while searching for timestamp: 3600
...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7566576900] st: 0 edit list 1 Cannot find an index entry before timestamp: 3600.
Saving project...
Saving project...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/flowblade/Flowblade/projectaction.py", line 168, in run
    app.open_project(project)
  File "/usr/share/flowblade/Flowblade/app.py", line 619, in open_project
    init_project_gui()
  File "/usr/share/flowblade/Flowblade/app.py", line 509, in init_project_gui
    gui.media_list_view.fill_data_model()
  File "/usr/share/flowblade/Flowblade/guicomponents.py", line 1115, in fill_data_model
    media_file = PROJECT().media_files[file_id]
KeyError: 313

**Comment by Pyork** [comment]
I were able to export XML while opening the project and before Flowblade stucks.
Then I moved to Shotcut. I had only only to complete the relative paths.
Thank you anyhow, namaste.

**Comment by jliljebl** [comment]
Unfortunately at this point I am unable to come up with a theory why this problem occurs but thanks for providing information on his issue, I will give this further attention after next release.
