### ISSUE TITLE
Rendered Cross Fades have jumpy ending sometimes

### ISSUE THREAD

**Issue by neltnerb** [jliljebl/flowblade-forum#103]
It is irregular, but for some reason when I do a transition between two video files it gives no errors or warnings but the last two frames are from the first clip instead of the second clip. If I merely make the transition two frames shorter it looks perfect.

I suspect a rounding error on frame rates myself, I told it to use 30 frames with video at 29.97fps (original videos were the same frame rate). Other times it renders the full transition properly.

Example rendered transition:
https://user-images.githubusercontent.com/429009/107285561-5eb62500-6a2d-11eb-866c-b86bcc0359a1.mp4

Flowblade version 2.4.0 on Ubuntu 20.04 and Pop_OS 20.04.

**Comment by jliljebl** [comment]
Ok, will give this a look, but this is could be quite hard to fix.
