### ISSUE TITLE
Does not preview the fixed images in JPG or PNG

### ISSUE THREAD

**Issue by daxtas** [jliljebl/flowblade-forum#109]
I have version 2.8.2 in deb
Ubuntu 2.4.2.
NVIDIA 460 driver and CUDA 11
JPG and PNG images come out blank
I tried with other editing software and do not have this problem
I lack any dependency? I added some that I did not owe.

**Comment by jliljebl** [comment]
Yeah, this is fortunately one of those "works here, can't reproduce" issues. I don't know what "Ubuntu 2.4.2" is, probably "Ubuntu 20.4.2" but that definitely should work. You can try Flatpak installation on Ubuntu, see: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md

**Comment by mathmethman** [comment]
I have this same problem.

When I last used Flowblade a few weeks ago it worked OK. Now when I add an image it appears as a white blank - and not just in the media tab but also when added to the video. I have changed no settings in the meantime.
If I load a previous .flb file the pictures appear OK in the media tab, but the video monitor is corrupted in that it has white space where there should be pictures (and there is a knock-on effect regarding some of the later synchronising of later components.)

**Comment by jliljebl** [comment]
I'll be doing tests before release to see if I can hit this but so far no reproduction.

**Comment by jliljebl** [comment]
I'll add a a bug issue in project link to  this and close here.
