### ISSUE TITLE
[2.8] 4 character limit in 'Position Scale' filter input?

### ISSUE THREAD

**Issue by bertiebaggio** [jliljebl/flowblade-forum#110]
Hi,

I have just started using Flowblade for a reasonably low-complexity project. It looks impressive so far! :) As I am new to it  would be happy to be corrected on usage or terminology.

The issue I have run into came up while trying to have an image move from above the frame onto the (1920x1080) frame, using keyframes. To get the image above the video frame, I used the **Transform → Position Scale** filter. I would like to change the Y coordinate to -1080 (it is an image 1080 pixels tall). However, the input on the Y coordinate box in that filter seems to only permit 4 characters, and as such it appears the minimum value is -999. I can drag and drop the box above the frame, but that throws off the X coordinate, and when I change the X coord to what it should be in the text box, that resets the Y coordinate to what it was before drag and drop.

Is this intended behaviour? Is there another way to achieve what I am trying to do?

Thanks in advance

![flowbladeycutoff](https://user-images.githubusercontent.com/7524620/114700008-e6aff800-9d18-11eb-8673-3fbe296f59ad.jpg)

**Example**:

![flowblade-y-x-reset](https://user-images.githubusercontent.com/7524620/114701404-ae111e00-9d1a-11eb-8d93-cac3928ab1f5.gif)

**Comment by jliljebl** [comment]
Ok, I will test, we may have bad UX here. There are other things going on, but I will return to this before next release to possibly fix issues.

**Comment by bertiebaggio** [comment]
Thanks for checking in on this, much appreciated :)

**Comment by jliljebl** [comment]
Yes, this was working the way you described and it was clearly bad UX. This is fixed in repo now and will be in 2.10 coming out in June. Thanks for the report.

**Comment by bertiebaggio** [comment]
That's great, thank you for taking the time to look into and fix this 😊
