### ISSUE TITLE
Issue with rendering sped up clips

### ISSUE THREAD

**Issue by Disaster2life** [jliljebl/flowblade-forum#112]
I recently started using flowblade for a recent editing project, and I needed to speed up a series of clips and when I used the in build thing for it, the task appeared in the jobs tab but even after leaving it for 30 minutes it never went past 0% any one else having this issue or is it just me? I am using the basic settings, I just upped the threat count to 2 in the settings, I am using PopOS with an Intel i7-4700U processor, would be thankful of any help.

**Comment by jliljebl** [comment]
I copied your comment in our render Issue sticky thread https://github.com/jliljebl/flowblade/issues/924 since this is a bug report, and those are hadled there. Thanks for the report.
