### ISSUE TITLE
 Creating transitions gives "not enough frames"

### ISSUE THREAD

**Issue by lonelylinux** [jliljebl/flowblade-forum#15]
This editor is already head and shoulders above everything else I can find for linux video editing.

I'd like to know when it's planned for the transition effect to function?

Right now, the transitions feature seems to think there's no video present, always says "not enough frames".

**Comment by jliljebl** [comment]
There needs to be overlap between clips to make a transition so mix can be made between media. If there is no media a transition cannot be made.

**Comment by welbinator** [comment]
I have the same issue. Overlapping clips doesn't help. It just says one clip has 500 frames to work with and the other has 0.

It's also frustrating that there is no visual indication that the two clips are indeed overlapping. Visually, it looks like it just shrunk down the first clip.

You should look at how WeVideo handles transitions. It's a 1000 times easier. I still haven't even figured out how to add a transition in Flowblade, which is a deal breaker. I can't not have transitions in my videos.

**Comment by jliljebl** [comment]
I created a visual guide for this problem https://github.com/jliljebl/flowblade-forum/issues/32

Closing this as duplicate.
