### ISSUE TITLE
Is it possible to render SRT file?

### ISSUE THREAD

**Issue by cnoam** [jliljebl/flowblade-forum#150]
I have an SRT (or SBV) file which I want to render in the video (at the correct time stamps of course).  

Is there a way to do it (in v 2.10+) ?

If not, can you hint which code should I touch? probably Generators.  If I create a new video track, it will cover the other tracks, so rendering should be using mask or on the existing track.

PS: How can I hide/delete tracks?

thanks!

**Comment by jliljebl** [comment]
1) I have an SRT (or SBV) file which I want to render in the video (at the correct time stamps of course).
 A: Not supported Flowblade, I think KDEnlive does work these. I'll look into adding support for these, but if 

2) How can I hide/delete tracks?
A: You can disable tracks by clicking on the screen and loudspeaker icons in tracks column or lete top most tracks by changing track count menu item Sequence->Change tracks count...In uocoming version 2.12 you will able to delete tracks from the middle row left *Tracks* menu.

**Comment by cnoam** [comment]
Thanks. If anyone also has the same need (rendering one or more SRT/SBV files) I used Shotcut (https://shotcut.org/).  I converted the SRT to MLT (the XML used by Shotcut), then added them to a new video track. It worked flawlessly (transparency and all).  Will be happy to see it also in Flowblade!
