### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by Pintaio** [jliljebl/flowblade-forum#156]
Hi
I've installed flatpak Flowblade in Linux Mint 22, but it's UI language is a mixture of English and Spanish language: some strings are correctly translated into Spanish, but others are in English.
I've seen at Github (flowblade-trunk/Flowblade/locale/es/LC_MESSAGES/flowblade.po) that strings are translated into Spanish.

So, why it is not working correctly?

**Comment by jliljebl** [comment]
Ok, will look into this. If there are actually some Spanish translations that exist, but are not used, I'm sure I can get them working for next release.

**Comment by jliljebl** [comment]
I opened this as bug port in project the Github page: https://github.com/jliljebl/flowblade/issues/1171 I'm closing this here.
