### ISSUE TITLE
Click on rendering MPEG-2 8000Kb/s 48Khz

### ISSUE THREAD

**Issue by danjde** [jliljebl/flowblade-forum#16]
Hi Devs!
First of all my compliments for your excellent work! For some years now Flowblade has improved a lot! Only the Filter section is very small and it's really hard to manage the cursors :-)

Then, going to the topic, I'm merging a video from yt and an audio same from yt but from a different video, and rendering MPEG-2 8000Kb/s 48Khz obtain some click audio, and some mute parts, that from the editor are not present.
I've try to turn down the volume from the mixer but with no luck.
I noticed that in the editor the audio is synchronized differently from the rendered video.
Moreover the video track come from a 24 fps video, and the audio track come from a 29.97 fps video. 
I've separated the audio from the 29.97 fps video.
I synced the audio with the reference clip, but nothing.
I've update to Flowblade 2.2 but nothing.

Again I've try rendering MPEG-4 8000Kb/s 48Khz, and the click are almost absent and no mute space.

What might it depend on?
Do you want a link to the rendered video?

I'm using Linux Ubuntu 16.04 and Flowblade 2.2

Many thanks!

Davide

**Comment by danjde** [comment]
Hi Devs,
I've try several preset, exporting and importing wav audio too, without success.
The only way (for me) was to rendering via H264/mp4.

Thanks!

Davide

**Comment by jliljebl** [comment]
Hi, as lead developer I'm currently in middle of porting the application to Python 3, which may take some weeks still. I have had similar audio problems sometimes, and occasionally the problem happened when there was no audio data on the very first frame and could be fixed by adding some audio data there, but this may not be your case.

If you can take a screenshot of the very beginning of your timeline that may help to reproduce this, currently I am not having this issue on my system.

**Comment by danjde** [comment]
Hi jliljebl and thanks for your feedback.
If you want to test and reproduce the issue, here you can download the "flb" file: https://server.3x1t.org/cloud/index.php/s/gD5zwG52bR3Gsrg
here the video track: https://server.3x1t.org/cloud/index.php/s/XQKCKPMAzxLbons
here the video for audio track: https://server.3x1t.org/cloud/index.php/s/Ro8edAbgDMnWnEz

I've found another two strange issue: 
1) importing this video in the timeline, Flowblade ask me if change to the file profile, answering yes Flowblade change the profile to 720x576 when the video source is 1280x720: https://server.3x1t.org/cloud/index.php/s/w987bSqTTNoYY3Q
2) As you can see from the second screenshot, in the project property the Profile project is HD 720p 24fps, but in Framerate for second is: 25.0: https://server.3x1t.org/cloud/index.php/s/on4E4S5xkdDpYTC


Thanks ;-)

**Comment by jliljebl** [comment]
Thanks for the additional data. Been working on Python 3 conversion but i will look at this more thoroughly during this development cycle.

**Comment by danjde** [comment]
;-)

**Comment by jliljebl** [comment]
Unfortunately I was never able to get around to this particular issue,, and I'm closing this as an out datged bug report. If problem persists, please file new Issue here: https://github.com/jliljebl/flowblade/issues
