### ISSUE TITLE
What does Select View Mode Do?

### ISSUE THREAD

**Issue by DroWnThePoor** [jliljebl/flowblade-forum#17]
Next to the Set Trim View options is Select View Mode: Vectorscope/Image/RGB Parade and an Opacity setting. Changing the options seems to do nothing for me, I never see a Vectorscope or RGB Parade overlay?

**Comment by jliljebl** [comment]
This is a bug report type of issue, the feature works just fine on my system.

I opened an Issue for it in Flowblade repository, we can continue this there: https://github.com/jliljebl/flowblade/issues/701

Please give following information:
1) Flowblade version (Help->About):
2) MLT version (Help->Runtime Environment):
3) Your distribution (Ubuntu, Debian, Mint etc.):
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Closing here as this not a forum type of question.
