### ISSUE TITLE
Some functions about add compositor

### ISSUE THREAD

**Issue by yichuang-zh** [jliljebl/flowblade-forum#36]
I tested the list below in the pop menu, but no change. Maybe I made wront operations.
If you have time, can you give me some guidance?

add compositor
- -alpha combiners-alpha XOR/Out
- -LumaToAlpha
- -blend - blend mode
    --screen
    --darken
    --lighten
    --multiply
    --saturate

     (What's the defference between normal and add)
    
- --hardlight

- -dissolve

- -picture in picture means a video inside another video or anything else? I can make a picture in picture video with this function, only this?

- -region
  --wipe type - rays
     ---align & distort & Force //what's the function?

- -blenders
     --hardlight
     --lighten
    --screen
    --subtract

------
I tested the list functions in a sample.flb file,  attached here.
[sample.zip](https://github.com/jliljebl/flowblade-forum/files/3882115/sample.zip)

My OS:
debian stretch 9.11/gnome/
flowbalde :
flatpak version 2.2.0
MLT version: 6.17.0
GTK verison: 3.24.11

**Comment by yichuang-zh** [comment]
My OS:
debian stretch 9.11/gnome/
flowbalde : 
flatpak version 2.2.0 
MLT version: 6.17.0
GTK verison: 3.24.11

**Comment by jliljebl** [comment]
I'm sorry but it is not possible to to answer such a massive question, there is a list of maybe 20 different functionalities here and trying to answer each item would burn many hours of time.

We do not have documentation on all Compositors, so the best thing to do is just to try out different stuff and if you are not seeing interesting functionality then just not use it.

**Comment by yichuang-zh** [comment]
I can understand that there is some trouble with this issue. My original intention is to understand all the functions of this software, and then write a manual about flowblade.
I understand that the development team may not have the time to take care of these specific usage issues. No problem, I'll explore it slowly.
Next, I first tried to upgrade the Chinese menu. There are some areas in the current Chinese menu that need to be improved.
