### ISSUE TITLE
Clone MLT repository OK, but Configure build failed.

### ISSUE THREAD

**Issue by yichuang-zh** [jliljebl/flowblade-forum#38]
**From here:** 
https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/creating_user_folder_bindings.md

**The step running command:**
` ./configure --prefix=<ROOT_DIR>/build --enable-gpl --enable-gpl3 --swig-languages=python`

**Then tips:**
`Found gcc version 9
awk: line 2: function lshift never defined
awk: line 2: function lshift never defined
awk: line 2: function lshift never defined
awk: line 2: function lshift never defined
Configuring framework:
Configuring modules:
Configuring modules/avformat:
Configuring modules/core:
Configuring modules/decklink:
Configuring modules/feeds:
Configuring modules/frei0r:
Package frei0r was not found in the pkg-config search path.
Perhaps you should add the directory containing [frei0r.pc]
to the PKG_CONFIG_PATH environment variable
No package [frei0r] found
Configuring modules/gtk2:
- GTK2 components not found: disabling
Configuring modules/jackrack:
Configuring modules/kdenlive:
Configuring modules/linsys:
Configuring modules/lumas:
- not explicitly enabled: disabling
Configuring modules/motion_est:
Configuring modules/ndi:
- NDI SDK not found: disabling
Configuring modules/normalize:
Configuring modules/oldfilm:
Configuring modules/opencv:
- not explicitly enabled: disabling
Configuring modules/opengl:
- movit not found: disabling
Configuring modules/plus:
- fftw not found: disable fft and dance filters
- libebur128 not found: using internal libebur128
Configuring modules/plusgpl:
Configuring modules/qt:
./configure: 43: qmake: not found
- Libexif not found, disabling exif features (auto rotate)
- Qt not found - disabling
Configuring modules/resample:
Configuring modules/rtaudio:
Configuring modules/sdl:
 - using SDL version 1.2.15
Configuring modules/sdl2:
- SDL2 development libs not found: disabling
Configuring modules/sox:
Configuring modules/swfdec:
- swfdec not found: disabling
Configuring modules/vid.stab:
- vid.stab not found: disabling
Configuring modules/videostab:
Configuring modules/vmfx:
Configuring modules/xine:
Configuring modules/xml:
Configuring mlt++:
Configuring swig:
GPLv3 license used`

**What can I do now?**
OS: KVMguest Ubuntu 19.10 / gnome 3.34.1

**Comment by yichuang-zh** [comment]
Or, there is another way to creating a translation?

**Comment by jliljebl** [comment]
Hi, you have not installed all the dependencies needed to build the bindings. It is possible that our instructions on these are missing something but the instructions are only meant as a rough guide 

Unfortunately giving support on building MLT bindings for Flowblade is not something that is in the scope of the project, building C libraries is skill that one needs to learn elsewhere.

You can work on the translations just by cloning the latest repo and using application like *POEdit* to work on  zh_CN or zh_TW *flowblade.po* file, see item 3. here:  https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/CREATING_TRANSLATION.md

You can send the edited *flowblade.po* file to me on e-mail and I can integrate it with the application.

**Comment by yichuang-zh** [comment]
OK.
Let me try.
If the translation can be done, I will email you.

**Comment by yichuang-zh** [comment]
How can I get your mail address ?

**Comment by jliljebl** [comment]
It's on project webpage but here it is: janne.liljeblad@gmail.com

ma 2. joulukuuta 2019 klo 12.33 yichuang驿窗 <notifications@github.com>
kirjoitti:
