### ISSUE TITLE
How to open a .fbl? 

### ISSUE THREAD

**Issue by bidetaggle** [jliljebl/flowblade-forum#46]
Hi, I'd like to better understand where and how the video clips (project data) linked to the .flb project file.
Is there a way to open a .flb? I opened it with a text editor but the result is pretty messy. Is there somewhere I can read more about how data storage is managed?

Thank you, good work btw :+1:

**Comment by jliljebl** [comment]
Hi, .flb files are files created by Python pickle() function. These are not meant  to be manually editable, but I believe it would be possible to edit them  if one would have detailed information how  pickle()  works.

**Comment by bidetaggle** [comment]
Ok, thanks
