### ISSUE TITLE
How to rotate a video recorded by mobile phone?

### ISSUE THREAD

**Issue by yichuang-zh** [jliljebl/flowblade-forum#48]
Someone ask me how to rotate a video recorded by mobile phone, I tryed to rotate a video form 1280*720 to 720*1280, below is is the modification process:

 Make a new profile: 720*1280 in menu **Edit - Profiles Manager**, import the recorded video(1280*720), then Add Filter - Transform - Rotate. In the Rotation box, input "90". 
Yes, the video was rotated, but the size is too small, not 720*1280, how do I achieve this?

**Comment by jliljebl** [comment]
This is a bit tricky, I don't have an answer right away without trying to actually to achieve this myself. I'll give this a session next and post info after that.

**Comment by jliljebl** [comment]
Ok, I was able to do this, but you need to use **ffmpeg** program in addition to Flowblade, Flowlbade does not really play nice with vertical video.

**Step 1. Convert material with ffmpeg**

Give this command in the folder you have your source video file, change  *input.mp4* and  *output.mp4* parts of command as needed.

    ffmpeg -i input.mp4 -vf "transpose=1" output.mp4

More info here: https://www.ostechnix.com/how-to-rotate-videos-using-ffmpeg-from-commandline/

**Step 2. Create user Profile**

Create new profile in Profiles Manager, note that you need to change display aspect values too, give these values:

*Width: 720
Height: 1280
Display aspect num.: 9
Display aspect num.: 16*

Now material is right sized if you have converted it with **ffmpeg**. Edit and render.

**Comment by yichuang-zh** [comment]
Got it!
Thank you~
