### ISSUE TITLE
Import png with transparent background

### ISSUE THREAD

**Issue by allelopath** [jliljebl/flowblade-forum#66]
I have a png file with a transparent background. When I Add it as Media, the background is black.
How do I get it to be a transparent background?

**Comment by allelopath** [comment]
![RedX](https://user-images.githubusercontent.com/2244559/83474007-301c8f00-a448-11ea-8abf-c2613bcb02de.png)

**Comment by jliljebl** [comment]
Flowblade user Compositors to create composite images.

Drag image on timeline, right click and select **Add Compositor** and some compositor. Now the clip in the track below becomes visible.

In the "Media Panel" we are currently not showing any checkboard pattern for alpha transparency, maybe later.
