### ISSUE TITLE
Compositing text at specific time

### ISSUE THREAD

**Issue by allelopath** [jliljebl/flowblade-forum#70]
For this video, I want the text to appear at 00:13 and disappear about 00:16

https://drive.google.com/file/d/1viRJ6XtKVlvgaEk9Ds8s1cn1nyQRFsIG/view?usp=sharing

How is this accomplished?

**Comment by jliljebl** [comment]
Maybe this video can help with this question https://vimeo.com/427093600

Basically just out a clip from  00:13 and disappear about 00:16 and use a Compositor or avter 2.6 Standard Full ytrack Compositing mode and Fade filter.
