### ISSUE TITLE
Unable to delete fade-in (?)

### ISSUE THREAD

**Issue by jose1711** [jliljebl/flowblade-forum#71]
Hello,

somehow when learning flowblade I managed to create a file containing an effect (probably fade-in) that I am unable to delete. Can you please help and describe how I could've run into this situation?
[untitled.zip](https://github.com/jliljebl/flowblade-forum/files/4822104/untitled.zip)
Thanks. 
jose

**Comment by jliljebl** [comment]
Ok, will look at this. We are just doing release next week, will return to this after that.

**Comment by jliljebl** [comment]
I have the data and give this a go but I'm closing this as we don't handle bug reports her, If problem reappers file bug report here: https://github.com/jliljebl/flowblade/issues
