### ISSUE TITLE
thumbnails and preview screen are white

### ISSUE THREAD

**Issue by dexterdy** [jliljebl/flowblade-forum#82]
![Screenshot_20200829_153227](https://user-images.githubusercontent.com/28401039/91638043-ee7e8e80-ea0c-11ea-8408-8009439c3e79.png)
So I've been looking for a good video editor for Linux and flowblade seems like a good option, but when I loaded it up and loaded some images to test, I saw that all thumbnails where white. When I put some images into the timeline, I saw that the preview was white as well. 

The images are PNG. I am using kubuntu 20.04. I've got no clue what's causing this, but I can't really do much like this.

**Comment by jliljebl** [comment]
Ok, this is duplicate bug report for an issue that does not reproduce on my system. I have an bug Issue here: https://github.com/jliljebl/flowblade/issues/1018, please do furher comments there. Closing here as we don't handle bug reports here.
