### ISSUE TITLE
Help file does not load

### ISSUE THREAD

**Issue by landronick** [jliljebl/flowblade-forum#89]
Message: "Firefox can't find the file at /usr/share/flowblade/Flowblade/res/help/en/help.html"

Checking that path, I see there is a "help.html" file in the "help" folder, but no "en" folder. I tried creating an "en" folder and copying the "help.html" file into it, but then got "Firefox can't find the file at /usr/share/flowblade/Flowblade/res/help/en/en/help.html"
Clicking directly on the "help.html" file in the "help" folder brings up the same  "can't find" message.
This is on a RaspberryPi4 running the loboris image of Ubuntu Mate: Linux RaspberryPi 5.4.73~lobo-arm64+
On my main desktop running Manjaro Gnome the help file loads correctly. I'm sure it's just a minor tweak needed somewhere, but I don't know how to proceed.

**Comment by jliljebl** [comment]
There probably unfortunately won't be solution/help for this unless some takes time create a proper distro package for Flowblade on a RaspberryPi4, closing this question for now.
